// Datos ficticios para la demostración del CRM

export const getDashboardStats = () => ({
  contacts: 1247,
  deals: 89,
  tickets: 23,
  revenue: 125000,
})

export const getRecentActivities = () => [
  {
    description: "Nuevo contacto agregado: María González",
    time: "Hace 2 horas",
    type: "success",
    module: "Contactos",
  },
  {
    description: "Negocio cerrado: Proyecto Web Corporativo",
    time: "Hace 4 horas",
    type: "success",
    module: "Negocios",
  },
  {
    description: "Ticket resuelto: Error en sistema de pagos",
    time: "Hace 6 horas",
    type: "success",
    module: "Tickets",
  },
  {
    description: "Nueva compra registrada: Licencias de software",
    time: "Hace 1 día",
    type: "info",
    module: "Compras",
  },
  {
    description: "Reunión programada con cliente potencial",
    time: "Hace 2 días",
    type: "info",
    module: "Negocios",
  },
]

export const getContacts = () => [
  {
    id: 1,
    name: "Ana García",
    email: "ana.garcia@empresa.com",
    phone: "+34 600 123 456",
    company: "Tech Solutions S.L.",
    position: "Directora de Marketing",
    address: "Calle Mayor 123, Madrid",
    status: "active",
    avatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T15:30:00Z",
  },
  {
    id: 2,
    name: "Carlos Rodríguez",
    email: "carlos.rodriguez@innovatech.es",
    phone: "+34 610 234 567",
    company: "InnovaTech",
    position: "CEO",
    address: "Avenida de la Innovación 45, Barcelona",
    status: "prospect",
    avatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2024-01-10T09:15:00Z",
    updatedAt: "2024-01-18T11:45:00Z",
  },
  {
    id: 3,
    name: "María López",
    email: "maria.lopez@digitalcorp.com",
    phone: "+34 620 345 678",
    company: "Digital Corp",
    position: "Gerente de Ventas",
    address: "Plaza del Comercio 78, Valencia",
    status: "active",
    avatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2024-01-05T14:20:00Z",
    updatedAt: "2024-01-22T16:10:00Z",
  },
  {
    id: 4,
    name: "David Martín",
    email: "david.martin@startuplab.es",
    phone: "+34 630 456 789",
    company: "StartupLab",
    position: "CTO",
    address: "Calle de la Tecnología 12, Sevilla",
    status: "inactive",
    avatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2024-01-01T08:30:00Z",
    updatedAt: "2024-01-15T12:00:00Z",
  },
  {
    id: 5,
    name: "Laura Sánchez",
    email: "laura.sanchez@consulting.com",
    phone: "+34 640 567 890",
    company: "Business Consulting",
    position: "Consultora Senior",
    address: "Paseo de los Negocios 89, Bilbao",
    status: "active",
    avatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2023-12-28T16:45:00Z",
    updatedAt: "2024-01-19T10:20:00Z",
  },
  {
    id: 6,
    name: "Roberto Fernández",
    email: "roberto.fernandez@ecommerce.es",
    phone: "+34 650 678 901",
    company: "E-Commerce Plus",
    position: "Director de Operaciones",
    address: "Avenida del E-Commerce 156, Málaga",
    status: "prospect",
    avatar: "/placeholder.svg?height=40&width=40",
    createdAt: "2023-12-20T13:15:00Z",
    updatedAt: "2024-01-17T14:30:00Z",
  },
]

export const getDeals = () => [
  {
    id: 1,
    title: "Desarrollo Web Corporativo",
    client: "Tech Solutions S.L.",
    value: 25000,
    stage: "negotiation",
    probability: 75,
    expectedCloseDate: "2024-02-15",
    description: "Desarrollo completo de sitio web corporativo con sistema de gestión de contenidos",
    contactId: 1,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-25T15:30:00Z",
  },
  {
    id: 2,
    title: "Sistema CRM Personalizado",
    client: "InnovaTech",
    value: 45000,
    stage: "proposal",
    probability: 60,
    expectedCloseDate: "2024-03-01",
    description: "Desarrollo de sistema CRM personalizado para gestión de clientes y ventas",
    contactId: 2,
    createdAt: "2024-01-08T09:15:00Z",
    updatedAt: "2024-01-23T11:45:00Z",
  },
  {
    id: 3,
    title: "Consultoría Digital",
    client: "Digital Corp",
    value: 15000,
    stage: "closed-won",
    probability: 100,
    expectedCloseDate: "2024-01-20",
    description: "Consultoría para transformación digital y optimización de procesos",
    contactId: 3,
    createdAt: "2023-12-15T14:20:00Z",
    updatedAt: "2024-01-20T16:10:00Z",
  },
  {
    id: 4,
    title: "App Mobile E-Commerce",
    client: "E-Commerce Plus",
    value: 35000,
    stage: "qualification",
    probability: 40,
    expectedCloseDate: "2024-04-10",
    description: "Desarrollo de aplicación móvil para plataforma de e-commerce",
    contactId: 6,
    createdAt: "2024-01-12T13:15:00Z",
    updatedAt: "2024-01-24T14:30:00Z",
  },
  {
    id: 5,
    title: "Integración de Sistemas",
    client: "Business Consulting",
    value: 20000,
    stage: "negotiation",
    probability: 80,
    expectedCloseDate: "2024-02-28",
    description: "Integración de sistemas ERP con plataformas de terceros",
    contactId: 5,
    createdAt: "2024-01-05T16:45:00Z",
    updatedAt: "2024-01-22T10:20:00Z",
  },
]

export const getTickets = () => [
  {
    id: 1,
    title: "Error en sistema de pagos",
    description: "Los usuarios reportan errores al procesar pagos con tarjeta de crédito",
    priority: "high",
    status: "open",
    category: "technical",
    assignedTo: "Equipo Técnico",
    clientId: 1,
    clientName: "Tech Solutions S.L.",
    createdAt: "2024-01-25T09:30:00Z",
    updatedAt: "2024-01-25T14:15:00Z",
  },
  {
    id: 2,
    title: "Solicitud de nueva funcionalidad",
    description: "Cliente solicita agregar sistema de notificaciones push en la aplicación móvil",
    priority: "medium",
    status: "in-progress",
    category: "feature-request",
    assignedTo: "Equipo de Desarrollo",
    clientId: 2,
    clientName: "InnovaTech",
    createdAt: "2024-01-24T11:20:00Z",
    updatedAt: "2024-01-25T10:45:00Z",
  },
  {
    id: 3,
    title: "Problema de rendimiento",
    description: "La aplicación web presenta lentitud en la carga de reportes",
    priority: "medium",
    status: "resolved",
    category: "performance",
    assignedTo: "Equipo de Optimización",
    clientId: 3,
    clientName: "Digital Corp",
    createdAt: "2024-01-22T15:10:00Z",
    updatedAt: "2024-01-24T16:30:00Z",
  },
  {
    id: 4,
    title: "Consulta sobre facturación",
    description: "Cliente necesita aclaración sobre los conceptos incluidos en la última factura",
    priority: "low",
    status: "open",
    category: "billing",
    assignedTo: "Equipo Comercial",
    clientId: 5,
    clientName: "Business Consulting",
    createdAt: "2024-01-23T13:45:00Z",
    updatedAt: "2024-01-23T13:45:00Z",
  },
  {
    id: 5,
    title: "Solicitud de capacitación",
    description: "El cliente requiere sesión de capacitación para el nuevo sistema implementado",
    priority: "medium",
    status: "scheduled",
    category: "training",
    assignedTo: "Equipo de Soporte",
    clientId: 6,
    clientName: "E-Commerce Plus",
    createdAt: "2024-01-21T10:15:00Z",
    updatedAt: "2024-01-24T09:20:00Z",
  },
]

export const getPurchases = () => [
  {
    id: 1,
    title: "Licencias Microsoft Office 365",
    supplier: "Microsoft Corporation",
    category: "software",
    amount: 2400,
    quantity: 20,
    unitPrice: 120,
    status: "completed",
    orderDate: "2024-01-20T10:00:00Z",
    deliveryDate: "2024-01-22T14:30:00Z",
    description: "Licencias anuales de Microsoft Office 365 para el equipo",
    approvedBy: "Ana García",
  },
  {
    id: 2,
    title: "Equipos de Desarrollo",
    supplier: "TechStore S.L.",
    category: "hardware",
    amount: 15000,
    quantity: 5,
    unitPrice: 3000,
    status: "pending",
    orderDate: "2024-01-24T09:15:00Z",
    deliveryDate: "2024-02-05T12:00:00Z",
    description: "Laptops de alta gama para el equipo de desarrollo",
    approvedBy: "Carlos Rodríguez",
  },
  {
    id: 3,
    title: "Servicios de Hosting",
    supplier: "CloudHost Pro",
    category: "services",
    amount: 1200,
    quantity: 12,
    unitPrice: 100,
    status: "completed",
    orderDate: "2024-01-15T16:20:00Z",
    deliveryDate: "2024-01-16T08:00:00Z",
    description: "Servicios de hosting premium por 12 meses",
    approvedBy: "María López",
  },
  {
    id: 4,
    title: "Mobiliario de Oficina",
    supplier: "OfficeDesign",
    category: "furniture",
    amount: 8500,
    quantity: 1,
    unitPrice: 8500,
    status: "approved",
    orderDate: "2024-01-25T11:30:00Z",
    deliveryDate: "2024-02-10T10:00:00Z",
    description: "Escritorios, sillas y mobiliario para nueva oficina",
    approvedBy: "David Martín",
  },
  {
    id: 5,
    title: "Herramientas de Diseño",
    supplier: "Adobe Systems",
    category: "software",
    amount: 3600,
    quantity: 10,
    unitPrice: 360,
    status: "completed",
    orderDate: "2024-01-18T14:45:00Z",
    deliveryDate: "2024-01-19T09:30:00Z",
    description: "Licencias anuales de Adobe Creative Suite",
    approvedBy: "Laura Sánchez",
  },
  {
    id: 6,
    title: "Sistema de Seguridad",
    supplier: "SecureTech",
    category: "security",
    amount: 5200,
    quantity: 1,
    unitPrice: 5200,
    status: "pending",
    orderDate: "2024-01-23T12:10:00Z",
    deliveryDate: "2024-02-15T15:00:00Z",
    description: "Sistema de cámaras y control de acceso para oficinas",
    approvedBy: "Roberto Fernández",
  },
]
